#!/usr/bin/env python3
"""Render a Nextflow pipeline for a realization plan.

The number of protected artefacts is a property of the workflow being
evaluated, not of the adapter, so the pipeline is generated from the plan --
exactly as the DagOnStar task graph is assembled from it. A static ``main.nf``
would otherwise pin the evaluation to one DAG shape.

The generated script is written into the run directory and kept, so the
pipeline that actually executed is part of the run's artefacts.
"""

from __future__ import annotations

from pathlib import Path

HEADER = """#!/usr/bin/env nextflow

/*
 * Generated by nextflow_pipeline.py for the artifact classes of one
 * realization plan. Every protected artefact crossing a workflow edge passes
 * through nfr_apply.py, the same enforcement path used by the in-process
 * engines, and each invocation appends to the shared enforcement log.
 */

nextflow.enable.dsl = 2

params.plan = null
params.apply = null
params.mixer = null
// Tasks run in a fresh shell that has not activated our virtualenv, so the
// interpreter is passed in explicitly rather than resolved from PATH.
params.python = 'python3'
params.outdir = 'results'
params.log = null
"""

INGEST = """
process INGEST {{
    output:
    path 'raw.bin'

    script:
    \"\"\"
    {payload_command}
    \"\"\"
}}
"""

PROTECT = """
process PROTECT_{upper} {{
    input:
    path payload

    output:
    tuple path('{name}.nfr'), path('{name}.steps.json')

    script:
    \"\"\"
    ${{params.python}} ${{params.apply}} \\
        --plan ${{params.plan}} \\
        --artifact-class {name} \\
        --direction output \\
        --in ${{payload}} \\
        --out {name}.nfr \\
        --steps {name}.steps.json \\
        --log ${{params.log}} \\
        --stage protect:{name}
    \"\"\"
}}
"""

UNPROTECT = """
process UNPROTECT_{upper} {{
    input:
    tuple path(payload), path(steps)

    output:
    path '{name}.restored'

    script:
    \"\"\"
    ${{params.python}} ${{params.apply}} \\
        --plan ${{params.plan}} \\
        --artifact-class {name} \\
        --direction input \\
        --in ${{payload}} \\
        --out {name}.restored \\
        --steps ${{steps}} \\
        --log ${{params.log}} \\
        --stage unprotect:{name}
    \"\"\"
}}
"""

COMPUTE = """
process COMPUTE {
    input:
    path payload

    output:
    path 'computed.bin'

    script:
    \"\"\"
    ${params.python} ${params.mixer} ${payload} computed.bin
    \"\"\"
}
"""

PUBLISH = """
process PUBLISH {
    publishDir params.outdir, mode: 'copy'

    input:
    path payload

    output:
    path 'final.bin'

    script:
    \"\"\"
    cp ${payload} final.bin
    \"\"\"
}
"""


def render(classes: list[str], compute_stage: str | None, payload_command: str) -> str:
    """Build the pipeline text for one ordered list of artifact classes."""
    if not classes:
        raise ValueError("a plan with no artifact classes has nothing to enforce")

    parts = [HEADER, INGEST.format(payload_command=payload_command)]
    for name in classes:
        upper = name.upper()
        parts.append(PROTECT.format(name=name, upper=upper))
        parts.append(UNPROTECT.format(name=name, upper=upper))
    parts.append(COMPUTE)
    parts.append(PUBLISH)

    # Nextflow's pipe operator expresses the chain directly, so the generated
    # workflow body reads like the stage list it came from.
    chain = ["INGEST()"]
    for name in classes:
        chain.append(f"PROTECT_{name.upper()}")
        chain.append(f"UNPROTECT_{name.upper()}")
        if name == compute_stage:
            chain.append("COMPUTE")
    chain.append("PUBLISH")

    body = "\n        | ".join(chain)
    parts.append(
        "\nworkflow {\n"
        "    if (!params.plan || !params.apply || !params.mixer) {\n"
        "        error '--plan, --apply and --mixer are all required'\n"
        "    }\n"
        f"    {body}\n"
        "}\n"
    )
    return "".join(parts)


def write(path: Path, classes: list[str], compute_stage: str | None,
          payload_command: str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(classes, compute_stage, payload_command), encoding="utf-8")
    return path
